package xyz.telegram.depinalliance.common.constans;

/**
 * @author holden on 25-Jul-2024
 */
public interface ResponseMessageConstants {
  String USER_NOT_ACTIVE = "MSG_USER_NOT_ACTIVE";
  String DATA_INVALID = "MSG_DATA_INVALID";
  String NOT_FOUND = "MSG_NOT_FOUND";
  String HAS_ERROR = "MSG_HAS_ERROR";
  //Accounts
  String USER_POINT_NOT_ENOUGH = "MSG_USER_POINT_NOT_ENOUGH";
  String USER_POINT_SKILL_NOT_ENOUGH = "MSG_USER_POINT_SKILL_NOT_ENOUGH";
  String USER_POINT_OR_POINT_SKILL_NOT_ENOUGH = "MSG_USER_POINT_OR_POINT_SKILL_NOT_ENOUGH";
  //Missions
  String MISSION_CANNOT_CHECKIN_TODAY = "MSG_MISSION_CANNOT_CHECKIN_TODAY";

  //Devices
  String DEVICE_ITEM_NOT_FOUND = "MSG_DEVICE_ITEM_NOT_FOUND";
  String DEVICE_USER_NOT_FOUND = "MSG_DEVICE_USER_NOT_FOUND";
  String DEVICE_USER_CANNOT_ADD_MORE_ITEM = "MSG_DEVICE_USER_CANNOT_ADD_MORE_ITEM";
  //UPGRADE
  String SKILL_NOT_FOUND = "MSG_SKILL_NOT_FOUND";
  String USER_SKILL_NOT_FOUND = "MSG_USER_SKILL_NOT_FOUND";
  String USER_SKILL_MAX_LEVEL = "MSG_USER_SKILL_MAX_LEVEL";
  String USER_SKILL_WAITING_UPGRADE = "MSG_USER_SKILL_WAITING_UPGRADE";
  String USER_SKILL_ANOTHER_WAITING_UPGRADE = "MSG_USER_SKILL_ANOTHER_WAITING_UPGRADE";
  //
  String UPLOAD_WRONG_FORMAT = "MSG_UPLOAD_WRONG_FORMAT";
  String UPLOAD_IMAGE_EXCEPTION = "MSG_UPLOAD_IMAGE_EXCEPTION";
  //ITEM
  String ITEM_SELL_NOT_ENOUGH = "MSG_ITEM_SELL_NOT_ENOUGH";
  String ITEM_CANNOT_SELL = "MSG_ITEM_CANNOT_SELL";
  String ITEM_OPEN_NOT_ENOUGH = "MSG_ITEM_OPEN_NOT_ENOUGH";
}
