package xyz.telegram.depinalliance.common.constans;

/**
 * @author holden on 25-Jul-2024
 */
public interface ResponseMessageConstants {

  String DATA_INVALID = "MSG_DATA_INVALID";
  String NOT_FOUND = "MSG_NOT_FOUND";
  String HAS_ERROR = "MSG_HAS_ERROR";
  //Accounts
  String ACCOUNT_ADDRESS_INVALID = "MSG_ACCOUNT_ADDRESS_INVALID";
  String ACCOUNT_CODE_NOT_FOUND = "MSG_ACCOUNT_CODE_NOT_FOUND";
  String ACCOUNT_LINKED_TWITTER = "MSG_ACCOUNT_LINKED_TWITTER";
  String ACCOUNT_LINKED_TELEGRAM = "MSG_ACCOUNT_LINKED_TELEGRAM";
  String ACCOUNT_TELEGRAM_LINKED_SUCCESS = "MSG_ACCOUNT_TELEGRAM_LINKED_SUCCESS";
  String ACCOUNT_TELEGRAM_LINKED_ERROR = "MSG_ACCOUNT_TELEGRAM_LINKED_ERROR";
  String ACCOUNT_CLAIMED_SUCCESS = "MSG_ACCOUNT_CLAIMED_SUCCESS";
  String ACCOUNT_CLAIMED_ERROR = "MSG_ACCOUNT_CLAIMED_ERROR";
  String ACCOUNT_MUST_LINK_TELEGRAM = "MSG_ACCOUNT_MUST_LINK_TELEGRAM";
  String ACCOUNT_MUST_LINK_TWITTER = "MSG_ACCOUNT_MUST_LINK_TWITTER";
  //Missions
  String MISSION_CANNOT_CHECKIN_TODAY = "MSG_MISSION_CANNOT_CHECKIN_TODAY";
}
